### ISSUE TITLE
Severely lacking

### ISSUE THREAD

**Issue by jonbrouse** [bbrouse/brouse-wedding#1]
User story: As a relative I want a website so that I can follow along with your planning and actual wedding.

Acceptance Criteria: Functioning site with stock photos replaced with photos before, during and after the wedding.  

QA: Mom

:couplekiss:

:heartpulse::heartpulse::cupid::heartpulse::heartpulse:
:revolving_hearts::revolving_hearts::wedding::revolving_hearts::revolving_hearts:
:two_hearts::two_hearts::two_hearts::two_hearts::two_hearts:

:house_with_garden:

**Comment by bbrouse** [comment]
This. Fucking. Guy.
